[package]
name = "msdf-atlas-sys"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]

[build-dependencies]
cmake = "0.1.50"
fs_extra = "1.3.0"
bindgen = "0.66.1"
regex = "1"