[package]
name = "msdf-atlas-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1.50"
fs_extra = "1.3.0"
vcpkg = "0.2.15"
bindgen = "0.66.1"